### ISSUE TITLE
Uploaded code is not up to date with release version

### ISSUE THREAD

**Issue by Phenrei** [NightmareXIV/SelectString#3]
Hi, was looking to add some features to this but the version here is still the API 5 version. Can you push the newest code so I can work with it a little? Starting out was going to add - and = key support for items 11 and 12 (retainer menu quit most notably), and possibly look into other features. Been a real time saver going through ventures.

Thanks.

**Comment by Limiana** [comment]
Hey, it's done now. Thanks for contribution, if you'll come up with any!
The main reason why I'm not really developing this plugin much is that programmatically clicking on many things isn't supported by ClickLib and I don't really know how to find that stuff out. (so for example it would not work on Leves)

**Comment by Phenrei** [comment]
Thanks for the quick reply. I have no problem digging into ClickLib's innards and trying to enhance it, if it comes to it, but we'll see how it goes.

**Comment by Phenrei** [comment]
Just FYI, I have working selection on the other type of list menus, buggy but working selection in retainers (need to find a way to handle lower retainer counts and it's throwing some errors due I think in part to how the list loads, if you try to "click" too quickly even on retainers you have it pops up a message about you having to pay for that retainer), and really buggy but basic working on yes/no selectors. Issues with confirmation and it can even let you hit hidden "no" buttons on some screens. Hopefully I can polish up some of them and get another PR in soon.

**Comment by Limiana** [comment]
yep, thanks!
https://github.com/Ottermandias/Accountant/blob/main/Accountant.GameData/RetainerManager.cs here is some useful code for checking how much retainers player has

**Comment by Phenrei** [comment]
Thanks. I was also going to check YesAlready for how it handles confirmation and all that. Clicker has a .Confirm() but it's just...not working. Maybe just an old address, or something else weird. Anyway, updates Soon(tm).
