### ISSUE TITLE
Update 6.2

### ISSUE THREAD

**Issue by Ari0ner** [NightmareXIV/SelectString#5]
Hi! Awesome plugin, cant live w/o it! Do you plan to update?

**Comment by Limiana** [comment]
Hello, yes, I'll update it soon

**Comment by Ari0ner** [comment]
Hi! Any news on the update?

**Comment by Limiana** [comment]
Hello, updated it now, should be good. Apologies, savage ate all the time

**Comment by Ari0ner** [comment]
Haha, understandable, thanks! :)
